### ISSUE TITLE
Update ujson

### ISSUE THREAD

**Issue by alycejenni** [NaturalHistoryMuseum/eevee#8]
Getting the error referenced here while setting up VMs:
https://github.com/ultrajson/ultrajson/issues/346

It seems to be fixed by updating to version >2, but there might be other consequences that I haven't found yet.

**Comment by jrdh** [comment]
ooo fun. I've updated it on a local branch where I've been making some changes to eevee and it's been ok so far and I would have thought it wouldn't be a problem to update it before that gets merged down.
